theme: jekyll-theme-minimal
minimal_mistakes_skin: "dirt"
title: Sandy Schumann(PhD)
author:
  avatar   : "photo.png"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "London, UK" 
